### ISSUE TITLE
1.在配置ScriptableObject的.net路径的路径选择时发生了报错，2.在点击生成时没有生成配置文件

### ISSUE THREAD

**Issue by AegeanRagdolls** [LiuOcean/Luban_Unity_GUI#2]
![Uploading WPPHQ8$7QF8}RKLCI@}BF0N.png…]()
手动输入路径没有报错。

点击生成时，生成了配置的代码实体，但是没有生成对应的配置文件（之前可以正常构建配置，在今天无意中发现没有生成，我尝试更换构建配置的目录依然无法生成成功）

**Comment by LiuOcean** [comment]
图片没有上传上来噢。

**Comment by AegeanRagdolls** [comment]
![WPPHQ8$7QF8}RKLCI@}BF0N](https://user-images.githubusercontent.com/25722201/184566730-e3301cb8-5ca6-4298-b625-8bc3a0e9a4c8.jpg)

**Comment by LiuOcean** [comment]
Config 文件贴一下，我瞅瞅。感觉可能是环境问题。

**Comment by AegeanRagdolls** [comment]
![QQ截图20220815104503](https://user-images.githubusercontent.com/25722201/184570460-2f950005-7a26-40d7-b43d-81a5e0eba590.jpg)

**Comment by LiuOcean** [comment]
奇怪，看着也没问题。 你试试最新版的，现在不用填 dotnet 路径了。

**Comment by AegeanRagdolls** [comment]
嗯呢 感谢哈~  我回家试一下~ 话说昨天我突然发现生成不出来配置文件了 , 之前一直都是没问题的 .  但是配置的实体脚本可以正常生成 , 我使用命令行使用Luban生成了一下,是可以生成到目标目录下面的.

**Comment by EasierLu** [comment]
这个生成类型还需要勾上二进制数据，我最开始没注意这个选项也发现配置文件生成不出来。
