### ISSUE TITLE
配置完成后，执行命令报错  Required option 'conf' is missing.

### ISSUE THREAD

**Issue by BeyondR34CH** [LiuOcean/Luban_Unity_GUI#9]
但将预览的命令复制到项目根目录下的bat文件中执行却没有问题

**Comment by LiuOcean** [comment]
具体执行的命令贴出来。

**Comment by BeyondR34CH** [comment]
dotnet Luban/Luban/Luban.dll ^
--conf Luban/DataTables/luban.conf ^
-t client ^
-c cs-simple-json ^
-d json ^
-x outputCodeDir=Assets/Gen/Luban/Codes ^
-x outputDataDir=Assets/Gen/Luban/Jsons

**Comment by LiuOcean** [comment]
检查一下工具版本是否为最新。

**Comment by BeyondR34CH** [comment]
Luban与GUI均为最新，报错内容如图
<img width="600" alt="Snipaste_2023-09-23_12-50-50" src="https://github.com/LiuOcean/Luban_Unity_GUI/assets/66902312/9beed145-02b3-445f-8151-c3e0d6972d2c">

**Comment by LiuOcean** [comment]
dotnet 的配置项填全路径试试。xxx/dotnet.exe

**Comment by BeyondR34CH** [comment]
效果是一样的

**Comment by LiuOcean** [comment]
ok 我大概知道了。 我抽空在 Windows 上试试。 你先用 bat 吧。

**Comment by LiuOcean** [comment]
更新到最新在试下，我在 Win 上验证没问题了。 目前临时生成 bat 文件再执行，作为 workaround。

**Comment by BeyondR34CH** [comment]
ok 解决了👍辛苦
